---
- debug:
    msg: "oah-remove of oah.desktop"

- name: Remove ubuntu-desktop
  become: yes
  become_user: root
  shell: |
    apt-get remove -y nautilus nautilus-* gnome-power-manager gnome-screensaver gnome-termina* gnome-pane* gnome-applet* gnome-bluetooth gnome-desktop* gnome-sessio* gnome-user* gnome-shell-common zeitgeist-core libzeitgeist* gnome-control-center gnome-screenshot
    apt-get -y autoremove
    reboot
  ignore_errors: yes
  failed_when: false
