---
- debug:
    msg: "oah-reset of oah.desktop"

- name: Reomve ubuntu-desktop
  include_tasks: oah-remove.yml
  ignore_errors: true

- name: Install ubuntu-desktop
  include_tasks: oah-install.yml
  ignore_errors: true