---
- debug:
    msg: "oah-install of oah.desktop"

- name: install ubuntu-desktop
  become: yes
  become_user: root
  command: "{{ item }}"
  with_items:
          - apt-get -y update
          - apt-get -y upgrade
          - apt-get install -y --no-install-recommends ubuntu-mate-desktop
          - reboot
  ignore_errors: yes
  failed_when: false
